### ISSUE TITLE
Import bug on linux

### ISSUE THREAD

**Issue by zkov96** [moxie0/chapcrack#27]
~/chapcrack-master$ ./chapcrack.py radius -C ../forMinchevWiFi-01.cap -R ./new-def
Traceback (most recent call last):
  File "./chapcrack.py", line 6, in <module>
    from chapcrack.commands.CrackK3Command import CrackK3Command
  File "/home/zkov/chapcrack-master/chapcrack/commands/CrackK3Command.py", line 7, in <module>
    from chapcrack.crypto.K3Cracker import K3Cracker
  File "/home/zkov/chapcrack-master/chapcrack/crypto/K3Cracker.py", line 11, in <module>
    from passlib.utils import des
ImportError: No module named passlib.utils

**Comment by kAlmAcetA** [comment]
Did you install it (e.g. python setup.py install)? Provide `pip freeze`.

**Comment by zkov96** [comment]
Thanks, but I got new stack exceptions.
$ chapcrack radius -C ../#####WiFi-01.cap -R ./new-def
Traceback (most recent call last):
  File "/usr/local/bin/chapcrack", line 7, in <module>
    from chapcrack.commands.DecryptCommand import DecryptCommand
  File "/usr/local/lib/python2.7/dist-packages/chapcrack/commands/DecryptCommand.py", line 15, in <module>
    from chapcrack.state.PppStateManager import PppStateManager
  File "/usr/local/lib/python2.7/dist-packages/chapcrack/state/PppStateManager.py", line 12, in <module>
    from chapcrack.state.MppeStateManager import MppeStateManager
  File "/usr/local/lib/python2.7/dist-packages/chapcrack/state/MppeStateManager.py", line 7, in <module>
    from M2Crypto.RC4 import RC4
ImportError: No module named M2Crypto.RC4
$$$$$$$$$$$$$$$$$$$$$$$$$
Please, add all needs libs to your message.
